### ISSUE TITLE
NullpointerException while using code with Neural Network Model 

### ISSUE THREAD

**Issue by RamakrishnaAddanki** [jpmml/jpmml-postgresql#1]
Hi,

I am beginner in this Jpmml  and  i was testing my neural network model using this jpmml-postgresql i changed deployment descriptor and and code accordingly to my neural network model i.e,. i added the input and output fields as per my requirement and while running the select command by passing the inputs i am getting Error: java.lang.NullPointerException. do i need to change anything to use this code to work with Neural Network models. can you please help me out 

thanks in advance

**Comment by vruusmann** [comment]
> i am getting Error: java.lang.NullPointerException

It is impossible to provide a meaningful response on the basis of such error report. Please copy&paste the full stack trace of the NPE.

**Comment by RamakrishnaAddanki** [comment]
Thank you for reply 
i am unable to find stack trace of this exception in postgreSQL and i am getting the same error for other components like pig and hive also and i able to find stack trace of pig and i posted it in jpmml-pig issues
